preservim/vim-markdown

indent/mkd.vim

Clearly stated on `:help indentexpr`.

Remove nosmartindent: indentexpr overrules it.

---

README.md
ftplugin/mkd.vim

`help 41` recommends using just `<Plug>ScriptnameFunctioName` to allow users adding a custom keymap, without the parenthesis, so we should expose that type of interface as well.
This is a backwards incompatible change that may break user's `.vimrc` if they have custom maps, and should be done on a new tag.

Remove parenthesis from <Plug> maps

---

ftplugin/mkd.vim

- remove Markdown_ prefix from s: functions
- always add one empty line between commands and methods

Improve style of ftplugin/mkd.vim

---

.travis.yml

* Run tests against latest vim & stock.
* Fixes #201
From the language I understood you still wanted to test against stock & also latest vim 7.4 line. So that's what this does. You can later add any other version/config of vim by simply using another RVM.

Build latest vim quickly from git mirror.

---

CONTRIBUTING.md

This is a followup to cirosantilli's comments on issue [#187](https://github.com/plasticboy/vim-markdown/issues/187).
By the way, GFM seems to no longer add line breaks for single newlines, so there doesn't seem to be any reason not to wrap text to less than 79 characters per line. However, to avoid breaking style with the rest of the README, I unwrapped the new text anyway.

README.md: add a section about issue reporting

---

registry/markdown.yaml

Seems the "indent" was forgotten, any reason behind it?

Add the indent part of the plugin to the registry

---

ftdetect/markdown.vim

. for multiple filetypes does not work with autocmd.
There seems to be no known workaround:
http://vi.stackexchange.com/questions/4893
This is a breaking change as it would break user scripts
who used autocmd, but we have already broken them
with this compound filetype, so let's just finish the job.
Semi-reverses: https://github.com/plasticboy/vim-markdown/pull/217

Use just markdown as filetype.

---

README.md
after/ftplugin/markdown.vim
test/python-folding.vader

As a python-mode user in my day-to-day work, I would like the folding styles of vim-markdown and python-mode to match, so that there's less cognitive overhead in switching between my two most frequently-used contexts.
To this end, I've made a distinct set of folding logic, keyed off of the `g:vim_markdown_folding_style_pythonic` variable, so that using this style is opt-in.
I've not included tests, as there were no existing tests for folds, and I wasn't familiar enough with Vader to know how to write them without some examples. If that's a blocker, I can and will put in the time to learn how to write them.
_And here's a cute animal picture for your troubles:_

Add support for python-mode style folding

---

.gitignore
.travis.yml
CONTRIBUTING.md
Makefile
doc/vim-markdown.txt
registry/markdown.yaml

Add a make rule to generate vim help file.
I tested some auto generate tools.
It seems [vim-tools](https://github.com/xolox/vim-tools) works fine with `README.md`.
#197

Generate vim help from README.md using vim-tools

---

README.md
after/ftplugin/markdown.vim
ftplugin/markdown.vim
test/folding-toc.vader

Fix bug that occurs when hash comments are used in fenced code blocks.
Fix same problem that occurs when building a TOC with the :Toc command.
Add flag that allow the user to set folding level, by default set to 1.

Fix bug related to folding and hash comments

---

.travis.yml
README.md
ftplugin/markdown.vim
test/toc-autofit.vader

Allow the user, to set an option, to have the TOC window shrink its size
in order to auto-fit to contents.

Implement TOC window auto-fit

---

README.md
syntax/markdown.vim
test/syntax-singleline.vader

By default text emphasis works across multiple lines until a closing token is found. This PR adds an user option to restrict text emphasis to a single line (ie, for it to be applied a closing token must be found on the same line).

Add option for singleline emphasis

---

syntax/markdown.vim
test/syntax.vader

Enables domain names that start with digits

Fix URL syntax regex

---

README.md
doc/vim-markdown.txt
indent/markdown.vim
test/indent-new-list-item.vader
test/indent.vader

before the pull request, we cannot configure new list item indent because it was fixed. i always insert 2-space indent for new list item, so i'd like to make it configurable.
i didn't change default behavior (the original number of spaces was 4, so i set default as 4).
You can adjust a new list indent. For example, you insert a single line like below:
```
* item1
```
Then if you type `o` to insert new line in vim and type `* item2`, the result will be:
```
* item1
* item2
```
vim-markdown automatically insert the indent. By default, the number of spaces of indent is 4. If you'd like to change the number as 2, just write:
```vim
let g:vim_markdown_new_list_item_indent = 2
```

Make new list item indent configurable

---

ftplugin/markdown.vim
test/syntax.vader

I usually see fenced code block with a language specifier followed by \`\`\` and some whitespace. This pull request supports highlighting them.

Support more general fenced code block

---

README.md
ftplugin/markdown.vim

Added a shortcut called `ge` that is similar to `gx` except that it
opens the file under the cursor for editing in Vim. This is particularly
useful when editing markdown that contains relative links to other
markdown files.

Implement "edit link in Vim" shortcut

---

syntax/markdown.vim
test/syntax.vader

Thanks for this great plugin :)
Currently, Link and InlineURL not highlighted in Headings/Blockquotes.
So I tried some fixes for myself and create PR.
Heading, bold, etc within blockquotes also reqiure highlighting.

Highlight mkdLink, mkdInlineURL in Headings

---

README.md
after/ftplugin/markdown.vim
doc/vim-markdown.txt

Adds the ability to set `g:vim_markdown_override_foldtext = 0` to disable setting foldtext when running with pythonic fold styles.  Handy if you already have a custom foldtext defined and don't want it overwritten.

Add option to disable foldtext override.

---

syntax/markdown.vim

The syntax "mkdListItem" was matching up to the end of the following white spaces after *, +, etc..
It seems like this is the cause of issue #296.
This commit shortens the matching region and fixes #296.

Fix the matching region of mkdListItem.

---

README.md
ftplugin/markdown.vim

Gitlab uses markdown in an interesting way. If you want to create a link
to the page "linked-to-page" you might do this:
`[Linked To Page Title](linked-to-page)`
And not,
`[Linked To Page Title](linked-to-page.md)`
This change is about having the "ge" command work on wiki links
constructed in this way, and provides consistency between how gitlab
works and vim-markdown works.
It also makes the file open relative to the file you are linking from, which is a sensible change.
The default behaviour is not affected.

Option to not require .md extensions in markdown links

---

README.md
ftplugin/markdown.vim

This commit allows ge to follow named anchors in links of the form
file#anchor, where file may omit the .md extension as usual.
Two global variables control the operation of this feature:
vim_markdown_follow_anchor: a flag that tells vim-markdown whether
to attempt to follow a named anchor in a link or not. When this is
1, and only if a link can be split in exactly two parts by the
pattern '#', then the first part is interpreted as the file and the
second one as the named anchor. After the file is opened, the anchor
will be searched.
vim_markdown_anchorexpr: if available this expression will be
evaluated substituting v:anchor with a quoted string that contains
the anchor to visit. The result of the evaluation will become the
real anchor to search in the target file. This is useful in …

Follow named anchors with ge

---

syntax/markdown.vim

Consider any line beginning with 3 or more of '*', '-', or '_' with
possible spaces before and between, possibly followed by zero or more of
the previously matched symbols or spaces to be a horizontal rule.

Change mkdRule match syntax to be more liberal

---

ftplugin/markdown.vim

Ensure the commands are executed only for Markdown buffers.
This fixes the autocommands being registered for all buffers, which should not happen. It also generated an unexpected side effect in the case of the `BufUnload` autocommand: deleting another buffer would trigger the autocommand but the current buffer `%` may be an open Markdown file (see `:help BufUnload`), and then `s:MarkdownClearSyntaxVariables()` (introduced in 156e0bfe4e68b01e28aee884bf4e69a34d3e7b1a) would be called in the Markdown buffer, creating issues with the syntax highlight of fenced blocks.

Make autocommands buffer-local

---

syntax/markdown.vim

Currently, frontmatter that looks like this:
```
---
foo: bar
...
```
doesn't work properly, as the `...` doesn't end the YAML syntax highlighting. This PR corrects that behaviour, so now either `---` or `...` can end a YAML frontmatter block.
There should be no backwards compatibility issues here, since a line containing only `...` is not valid YAML apart from marking the end of a document.
Fixes #295.

Support YAML frontmatter that ends with "..."

---

README.md
indent/markdown.vim

This PR adds a new option, `g:vim_markdown_auto_insert_bullets`, that disables the automatic bulletpoint insertion which is causing issues with text wrapping. The option is enabled by default to preserve backwards compatibility.
With the option enabled (the default), the behaviour is as before. If the option is disabled, bulletpoints are no longer automatically inserted, either when pressing `<Enter>` or when wrapping text with `gq`. Behaviour of blockquotes is not changed.
The new documentation for the option also suggests to set the new list item indent (`vim_markdown_new_list_item_indent`) to 0, as otherwise you will have to erase the indent each time you want to add a new bulletpoint.
Fixes #232. (Also see commit 642730fccce7e78c995389f3c430747d266efa96, from which this PR was …

Add option to disable automatic bullet insertion

---

syntax/markdown.vim

PR #374 introduced a bug which would cause any line containing exactly three characters to be highlighted as the end of a YAML frontmatter block; this commit fixes that, so that only three dots will end the block.

Fix detection of YAML frontmatter ending with "..."

---

ftdetect/markdown.vim

**Bug**: Using `vim --startuptime ~/time.log name.md` would show multiple
sourcing of syntax/markdown.vim indicating unnecessary startup cost.
**Cause**: As of vim/vim@7d76c804af900ba6dcc4b1e45373ccab3418c6b2, vim uses
.md for markdown instead of modula2. Since vim-markdown was using `set
filetype`, it was sourcing the files a second time after vim's runtime
files had already set the filetype.
**Resolution**: Using `setfiletype` prevents this double sourcing. To remain
backwards compatible, we remove the .md filetype detection for modula2
on old versions.
Related to sheerun/vim-polyglot#290.
Tested .md ftdetection with vim 7.4.052 and 8.1.527.

Prevent repeated sourcing of syntax

---

syntax/markdown.vim

This is not in standard markdown, but I think it is popular enough.
I do not make it compitible with other syntax(bold, italic, etc.),
this is only a suggestion.
Please forgive my poor English.

Add support for strike through which is supported by GFM

---

syntax/markdown.vim

Why
---
Strikethrough was only matching if the strikethrough happened to occur in a list
How
---
Add `mkdStrike` and `htmlStrike` to `mkdNonListItem` cluster

Syntax: Fix strikethrough

---

test/vimrc

The default value of runtimepath includes ~/.vim and ~/.vim/after.  Configuration in those directories can interfere with tests.  Remove those directories from runtimepath to make the tests hermetic.

Testing fix

---

after/ftplugin/markdown.vim
ftplugin/markdown.vim

When syntax highlighting is enabled for fenced code blocks, the syntax
highlighting of the language in the code block can overwrite folding
configuration, breaking Markdown folding.  Reinitialise Markdown folding
configuration every time syntax highlighting is refreshed to ensure that
Markdown folding works.
Lightly tested manually with files where folding was unreliable.

Folding fix

---

syntax/markdown.vim
test/syntax.vader

This is a follow-up of https://github.com/plasticboy/vim-markdown/commit/5c9ce6b5230654c73d3bc3311f9dff7c4404f228 which fixed #311.
The following is the content for test and actual GitHub rendering:
``` markdown
``a\`` b ``c`\`1`` d
```
``a\`` b ``c`\`1`` d

Fix double code quotes with backslashes

---

doc/vim-markdown.txt

It's useful for executing `:help` against global variables directly.

Mention related global variables in document

---

README.md

I set `conceallevel=0` in .vimrc, as well as `g:vim_markdown_conceal = 0` but code fences were still being hidden. I could not find this option documented anywhere, so I went to the source code. Adding the `g:vim_markdown_conceal_code_blocks = 0` fixed my problem, and I assume other people will want to find this in the future.

document `conceal_code_blocks` in README.md

---

Makefile
README.md
doc/vim-markdown.txt

See https://github.com/plasticboy/vim-markdown/pull/429#issuecomment-485348064.
html2vimdoc doesn't handle code snippets surrounded with ` ``` ` under the list properly, so I replaced code snippets with indented ones.

Generate IDs of global variables

---

after/ftplugin/markdown.vim

Line 58 is the real change. It makes it so the folding level of a heading corresponds to the level of the heading. 
Previously, an h1 would not be folded, while and h2 would be folded at level 1. This would make the plugin unusable when editing large documents where the absolute heading level matters, such as Markdown that gets rendered to LaTeX. (If you'd like, I can elaborate on this opinion.)
I also added a bunch of comments for my own benefit when I was looking for the code that did the translation from pound signs to heading level. I'll take those out if they're a pain.
This seems related to #130.

Enable Pythonic Folding of Level 1 Headings

---

syntax/markdown.vim

`mkdStrike` wasn't matching in places where it should, because `htmlStrike` was included in `mkdNonListItem`'s `contains` instead.
Also allow strikethrough delimiters to be concealed.

Fix strikethrough

---

syntax/markdown.vim
test/syntax.vader

Fix #419.
This is a minimal change that replacing `\S*` with `[^] \t]*`, to stop `mkdInlineURL` consuming a `]` character.

Fix mkdInlineURL not to highlight after closing brackets

---

README.md
ftplugin/markdown.vim
test/folding-toc.vader
test/insert-toc.vader

There wasn't any open issue for this feature request, but I thought of implementing it anyway, as I find it very useful. Hopefully other people find it useful as well.
The `:InsertToc` command inserts a table of contents at the current line in the markdown buffer. The `:InsertNToc` command behaves like `:InsertToc,` but the format of h2 headers in the table of contents is a numbered list, rather than a bulleted list.
An optional argument can be used to specify how many levels of headers to display in the table of content, e.g., to display up to and including h3, use `:InsertToc 3`.
Documentation and unit tests added as well.

Add `:InsertToc` and `:InsertNToc` commands

---

syntax/markdown.vim

The old patterns would match any start tag which began with `pre` or `code`. Because the end-tag then didn't match, the whole rest of the file was highlighted as code. These should ensure that only the specific tags `pre` and `code` are picked up while still allowing for attributes.
I've not added documentation or tests, as this is such a small tweak to existing patterns (and because I don't know enough vim scripting to write the tests, anyway.) Hopefully that's not a problem?

tweak html tag matching for code blocks

---

ftplugin/markdown.vim
test/syntax.vader

In Hugo, [code block fences can include extra options](https://gohugo.io/content-management/syntax-highlighting/#highlighting-in-code-fences) in them. This change allows these extra characters to be ignored such that the highlighting still works. ie.
```bash {linenos=table,hl_lines=[8,"15-17"],linenostart=199}
#!/bin/bash
....
```

feat: Allow characters after code fence language

---

ftplugin/markdown.vim

Forgot to remove a `echom` debugging command from PR #492 
Thanks to @petobens for pointing it out.

fixup: Remove debugging echo message

---

ftplugin/markdown.vim

Problem: TableFormat adds hyphens at the left of the indented table like
this:
```
| a | b |
--|---|---|
| x | y |
```
Solution: Replace only the spaces between pipes.

Fix TableFormat for indented tables

---

README.md
ftplugin/markdown.vim

This is to allow for NOT using `ge`, rather just stick with the built-in `gf` for editing files, with a mapping such as this:
```
autocmd FileType markdown nmap <buffer>gf <Plug>Markdown_EditUrlUnderCursor
```
Why edit if it exists:
:h gf
> If you do want to edit a new file, use: >
> :e <cfile>
> To make gf always work like that: >
> :map gf :e <cfile><CR>
Since Markdown_EditUrlUnderCursor behaves this way already
going with the edit always is a more logical fallback.

make Markdown_EditUrlUnderCursor fall back to builtin gf

---

README.md
doc/vim-markdown.txt
ftplugin/markdown.vim
test/map.vader

Shortcut key `]c` overrides diff-next-change jump.
Users can use diff-mode for Markdown files, so the shortcut should be another.

Change shortcut: MoveToCurHeader: `]c` -> `]h`

---

.github/workflows/reviewdog.yml
.github/workflows/vader.yml
.github/workflows/vint.yml
.vintrc.yaml
README.md
after/ftplugin/markdown.vim
ftdetect/markdown.vim
ftplugin/markdown.vim
indent/markdown.vim
syntax/markdown.vim
test/folding-toc.vader
test/vimrc

Besides adding the CI jobs, this also refactors much of the vimscript to pass lint tests and adapts the test suite to work on both VIM and NeoVIM.

Add CI‌ jobs to lint vimscript, run regression tests, and comment on PRs

---

ftplugin/markdown.vim
test/table-format.vader

Improved version of 6fe1a105302ad5b7a79e6346051c34dcc16cee70 that doesn't get fooled by colons.

Fix TableFormat for indented tables, version 2

---

ftdetect/markdown.vim

This reverts commit 18ed14af66ed1af7ecc612540b50acf51e55a23d.
Do not need `augroup` for `ftdetect`, see `:h ftdetect`, and
`filetypedetect` may is a autocmd group name.

Revert "refactor: Execute autocmd in group scope"

---

ftplugin/markdown.vim

When &syntax's value is OFF, vim doesn't load syntax files for the file. However, this plugin loads code block syntax highlighting rules even if the value is OFF. This behavior is inconsistent for users to disable syntax highlighting locally. For example, this causes on a modeline such as ``.
Use != to compare &syntax's value to use the same logic run on $VIMRUNTIME/syntax/synload.vim.

Disable code block syntax highlighting when syntax=OFF

---

README.md

The only reason you would need to use vim-toml or vim-json is if you use an old version of (Neo)Vim. As of today, you do not need those plugins.

Remove outdated advice for Vim plugins

---

after/ftplugin/markdown.vim

Minor fix for errors found with `:set debug=msg`, when `g:vim_markdown_frontmatter` is not set.

Handle missing frontmatter option

---

ftplugin/markdown.vim
test/syntax.vader

Allow fenced code block syntax highlighting to work in liquid buffers that have markdown subtype. This provides compatibility with vim-liquid.
Resolves #608

Fenced code highlight in liquid

---

syntax/markdown.vim
test/strikethrough.vader
test/syntax.vader

Changes
- highlights bold, italic, bold italic, strikethrough and footnotes inside headings.
This should fix #614, but not #635.

Add syntax highlighting to some elements inside headings

---

ftplugin/markdown.vim

For some reason `execute '/'.l:anchor` does not populate jumplist, so use builtin vim `search()` function

Fix jumping to anchor

---

README.md
doc/vim-markdown.txt
ftplugin/markdown.vim
test/table-format.vader

This seems like a valid table(at least in github):
```
header 1|header 2
--|--
data 1|data 2
```
rendered:
header 1|header 2
--|--
data 1|data 2
The solution in this pull request is to wrap all lines that don't have `|` at the beginning or the end.
I also added range call support. It doesn't change the implementation but allows to call `TableFormat` while having the selection.

add support for tables without borders

---

README.md
doc/vim-markdown.txt

Seems that the mappings for folding commands is still the vim default.  This updates the documentations. Fix #632

Fix mappings for folding in documentation

---

syntax/markdown.vim

If you write some C function spec as a `code` block in heading, it may break.
```markdown
foobar
```
The part of `**` is considered as a beginning of **bold** style.
Shouldn't you include `mkdCode` in `mkdHeadingContent` to avoid this?

Should contain `code` in headings

---

after/ftplugin/markdown.vim
ftplugin/markdown.vim

Text like below will break code fence.
~~~text
```text
~~~hoge~~~
```
```
~~~piyo~~~
```
```text
hogefugapiyo
~~~~
```
~~~
Fixed the check pattern, and fence ending check to compare with the fence beginning string.
`:Toc` command and text folding do work.
Can anyone fix syntax `syntax/markdown.vim`?

Code fence handling breaks if `~~~` appears in the fence
